add user id parameter to createPlaylist method
jwilsson/spotify-web-api-php pull request #265
Opened 2023-07-27 15:18 UTC by revoltek-daniel

Add the user_id parameter to the createPlaylist method like mentioned in the API docs https://developer.spotify.com/documentation/web-api/reference/create-playlist

2023-07-28 09:38 UTC, jwilsson requested changes
Thanks for contributing! 🎉 

I'm afraid this would be a breaking change in its current form, I've added a suggestion on how it could be solved instead.

2023-07-28 09:38 UTC, jwilsson commented on src/SpotifyWebAPI.php
> +    public function createPlaylist($userId, $options)
I'm afraid this would be a breaking change.

We could add a check to keep the backwards compatibility for a while and remove that check in the future, for example: 

```suggestion
    public function createPlaylist($userId, $options = [])
{
    if (is_array($userId) || is_object($userId)) {
        $options = $userId;
        $userId = 'me';
    }
```

2023-07-28 09:38 UTC, jwilsson commented on src/SpotifyWebAPI.php
> +        $uri = '/v1/' . $userId . '/playlists';
We usually wanna support passing a Spotify URI too, there's a helper method to extract the ID from it:

```suggestion
        $userId = $this->uriToId($userId, 'user');
        $uri = '/v1/' . $userId . '/playlists';
```

2023-07-28 09:56 UTC, revoltek-daniel commented on src/SpotifyWebAPI.php
> +    public function createPlaylist($userId, $options)
i've added your suggestions

2023-07-29 12:34 UTC, jwilsson commented
Thanks again for contributing! 🎉 

There seems to be some unrelated failing tests, I'll get this merged anyway and tag a new release.

2023-07-29 12:34 UTC, jwilsson approved these changes

2023-07-29 12:34 UTC, merged